CREATE TABLE IF NOT EXISTS {{table}}
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY
        (INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1),

    uuid uuid NOT NULL,

    external_id character varying(100),

    parent_external_id character varying(100),

    level integer NOT NULL DEFAULT 1,

    name character varying(255) NOT NULL,

    slug character varying(255) NOT NULL,

    is_leaf boolean NOT NULL DEFAULT false,

    description text,

    meta_title character varying(255),

    meta_description text,

    attributes jsonb NOT NULL DEFAULT '{}'::jsonb,

    image_url character varying(500),

    sort_order integer NOT NULL DEFAULT 0,

    is_active boolean NOT NULL DEFAULT true,

    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT {{prefix}}_pkey
        PRIMARY KEY (id),

    CONSTRAINT uq_{{prefix}}_external_id
        UNIQUE (external_id),

    CONSTRAINT uq_{{prefix}}_slug
        UNIQUE (slug),

    CONSTRAINT uq_{{prefix}}_uuid
        UNIQUE (uuid)
);

ALTER TABLE IF EXISTS {{table}}
    OWNER TO symfony;


COMMENT ON COLUMN {{table}}.id
    IS 'Внутренний идентификатор категории';

COMMENT ON COLUMN {{table}}.uuid
    IS 'Публичный UUID категории';

COMMENT ON COLUMN {{table}}.external_id
    IS 'Идентификатор категории во внешней системе или CSV';

COMMENT ON COLUMN {{table}}.parent_external_id
    IS 'Идентификатор родительской категории во внешней системе или CSV';

COMMENT ON COLUMN {{table}}.level
    IS 'Уровень вложенности';

COMMENT ON COLUMN {{table}}.name
    IS 'Название категории';

COMMENT ON COLUMN {{table}}.slug
    IS 'Уникальный URL slug категории, сформированный из названия и внешнего ID';

COMMENT ON COLUMN {{table}}.is_leaf
    IS 'Признак конечной категории, содержащей товары';

COMMENT ON COLUMN {{table}}.description
    IS 'Описание категории';

COMMENT ON COLUMN {{table}}.meta_title
    IS 'SEO title';

COMMENT ON COLUMN {{table}}.meta_description
    IS 'SEO description';

COMMENT ON COLUMN {{table}}.attributes
    IS 'Произвольные структурированные свойства категории в формате JSONB';

COMMENT ON COLUMN {{table}}.image_url
    IS 'URL изображения категории';

COMMENT ON COLUMN {{table}}.sort_order
    IS 'Порядок сортировки';

COMMENT ON COLUMN {{table}}.is_active
    IS 'Признак активности категории';

COMMENT ON COLUMN {{table}}.created_at
    IS 'Дата создания';

COMMENT ON COLUMN {{table}}.updated_at
    IS 'Дата последнего обновления';


CREATE INDEX IF NOT EXISTS idx_{{prefix}}_external_id
    ON {{table}} (external_id);

CREATE INDEX IF NOT EXISTS idx_{{prefix}}_parent_external_id
    ON {{table}} (parent_external_id);

CREATE INDEX IF NOT EXISTS idx_{{prefix}}_parent_external_active
    ON {{table}} (parent_external_id, is_active);

CREATE INDEX IF NOT EXISTS idx_{{prefix}}_level
    ON {{table}} (level);

CREATE INDEX IF NOT EXISTS idx_{{prefix}}_slug
    ON {{table}} (slug);

CREATE INDEX IF NOT EXISTS idx_{{prefix}}_sort_order
    ON {{table}} (sort_order);

CREATE INDEX IF NOT EXISTS idx_{{prefix}}_is_active
    ON {{table}} (is_active);

CREATE INDEX IF NOT EXISTS idx_{{prefix}}_is_leaf
    ON {{table}} (is_leaf);
