<?php
/** Explicit paid check of an existing task's frozen generation request; no account data or raw responses are printed. */
declare(strict_types=1);
require __DIR__.'/../vendor/autoload.php';
use App\Infrastructure\Workspace\GigaChatClient;
use App\Application\Workspace\AssessmentContract;
use Doctrine\DBAL\{DriverManager,Tools\DsnParser};
$db=DriverManager::getConnection((new DsnParser(['postgresql'=>'pdo_pgsql']))->parse(getenv('DATABASE_URL')));
$task=$db->fetchAssociative('SELECT generation_metadata,criteria_snapshot FROM catalog.tests WHERE id=?',[(int)($argv[1]??0)]);
if(!$task)exit(1);
$meta=json_decode($task['generation_metadata'],true);$snapshot=json_decode($task['criteria_snapshot'],true);
$trace=new Symfony\Component\HttpClient\TraceableHttpClient(Symfony\Component\HttpClient\HttpClient::create());
$client=new GigaChatClient($trace,getenv('GIGACHAT_AUTH_KEY'),getenv('GIGACHAT_SCOPE'),getenv('GIGACHAT_MODEL'),getenv('GIGACHAT_CA_FILE'));
try {
 $result=$client->json(AssessmentContract::GENERATION_INSTRUCTION,$meta['generation_request']);
 $shape=['compatible'=>$result['compatible']??null,'title_type'=>get_debug_type($result['title']??null),'assignment_type'=>get_debug_type($result['assignment']??null),'criteria_count'=>is_array($result['criteria_checks']??null)?count($result['criteria_checks']):null];
 echo json_encode($shape)."\n";
 (new AssessmentContract())->generation($result,$snapshot,array_column($meta['generation_request']['selection']['technologies'],'code'));
 echo "PASS: response matches frozen generation contract\n";
} catch(UnexpectedValueException $error) {
 // These messages are generated by our own validators, never by an HTTP/provider exception.
 echo 'Validator: '.$error->getMessage()."\n";
 if(isset($result)){
  echo 'Expected technology codes: '.json_encode(array_column($meta['generation_request']['selection']['technologies'],'code'))."\n";
  echo 'Technology codes match: '.(isset($result['required_technology_codes'])&&$result['required_technology_codes']===array_column($meta['generation_request']['selection']['technologies'],'code')?'yes':'no')."\n";
  foreach($snapshot as $i=>$c){$g=$result['criteria_checks'][$i]??[];echo 'Criterion '.($i+1).': code_matches='.(($g['criterion_code']??null)===$c['code']?'yes':'no').', competency_matches='.(($g['competency_code']??null)===$c['competency_code']?'yes':'no').', version_type='.get_debug_type($g['criterion_version']??null).', checks='.count($g['checks']??[])."\n";foreach($g['checks']??[] as $check)echo 'check id valid: '.(is_string($check['check_id']??null)&&preg_match('/^[a-zA-Z0-9_-]{1,80}$/D',$check['check_id'])?'yes':'no')."\n";}
 }
 exit(1);
} catch(Throwable $error) {
 if($error->getMessage()==='GIGACHAT_HTTP_422'){
  $secrets=[getenv('GIGACHAT_AUTH_KEY'),base64_decode(getenv('GIGACHAT_AUTH_KEY'))];
  foreach($trace->getTracedRequests() as $request)if(is_array($request['content']??null)&&isset($request['content']['access_token']))$secrets[]=$request['content']['access_token'];
  foreach($trace->getTracedRequests() as $request){if(!str_ends_with($request['url'],'/chat/completions'))continue;$content=$request['content']??[];$message=is_array($content)?($content['message']??$content['detail']??''):'';if(is_string($message))echo 'Sanitized validation diagnostic: '.substr(str_replace(array_filter($secrets), '[REDACTED]', $message),0,1500)."\n";}
 }
 echo 'Connection failure class: '.get_class($error).'; timeout='.(stripos($error->getMessage(),'timeout')!==false||stripos($error->getMessage(),'timed out')!==false?'yes':'no')."\n";exit(1);}
