<?php
declare(strict_types=1);
namespace DoctrineMigrations;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
final class Version20261008180000 extends AbstractMigration
{
    public function getDescription(): string { return 'Durable background jobs for GPT generation and evaluation'; }
    public function up(Schema $schema): void
    {
        $s = $this->connection->quoteSingleIdentifier($_ENV['DB_SCHEMA'] ?? 'catalog');
        $this->addSql("CREATE TABLE {$s}.assessment_jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            test_id BIGINT NOT NULL REFERENCES {$s}.tests(id) ON DELETE RESTRICT,
            operation TEXT NOT NULL CHECK(operation IN ('generate','evaluate')),
            status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','processing','done','failed')),
            lease UUID, executions INT NOT NULL DEFAULT 0 CHECK(executions>=0),
            created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(test_id,operation)
        )");
        $this->addSql("CREATE INDEX assessment_jobs_pending ON {$s}.assessment_jobs(status,updated_at)");
    }
    public function down(Schema $schema): void { $this->throwIrreversibleMigrationException('Assessment jobs must not be discarded.'); }
}
