<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260620221313 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Таблица catalog_table_versions для управления версиями таблиц категорий';
    }

    public function up(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $table = "\"{$schemaName}\".\"catalog_table_versions\"";

        $this->addSql("
            CREATE TABLE {$table}
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                table_name VARCHAR(255) NOT NULL,

                original_name VARCHAR(255) NOT NULL DEFAULT 'categories',

                version VARCHAR(50) NOT NULL,

                status VARCHAR(20) NOT NULL DEFAULT 'new',

                is_active BOOLEAN NOT NULL DEFAULT FALSE,

                switched_at TIMESTAMP WITHOUT TIME ZONE,

                rows_count INTEGER,

                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT catalog_table_versions_pkey PRIMARY KEY (id),

                CONSTRAINT uq_catalog_table_versions_table_name UNIQUE (table_name),

                CONSTRAINT chk_catalog_table_versions_status 
                    CHECK (status IN ('active', 'inactive', 'new', 'archived'))
            )
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.id
            IS 'Уникальный идентификатор записи'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.table_name
            IS 'Текущее имя таблицы в базе данных (например, categories_v2)'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.original_name
            IS 'Оригинальное имя таблицы (всегда categories)'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.version
            IS 'Версия таблицы (например, v2, v3, 20260121_120000)'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.status
            IS 'Статус таблицы: active - рабочая, inactive - отключена, new - новая (не включалась), archived - в архиве'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.is_active
            IS 'Флаг: TRUE - эта таблица сейчас используется как основная'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.switched_at
            IS 'Дата и время переключения на эту таблицу (для active таблиц)'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.rows_count
            IS 'Количество записей в таблице на момент создания/переключения'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.created_at
            IS 'Дата и время создания таблицы'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.updated_at
            IS 'Дата и время последнего обновления записи'
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_catalog_table_versions_status
            ON {$table} (status)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_catalog_table_versions_is_active
            ON {$table} (is_active)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_catalog_table_versions_table_name
            ON {$table} (table_name)
        ");

        $this->addSql("
            CREATE INDEX IF NOT EXISTS idx_catalog_table_versions_created_at
            ON {$table} (created_at)
        ");

        // Вставляем начальную запись для существующей таблицы
        $this->addSql("
            INSERT INTO {$table} (table_name, original_name, version, status, is_active, switched_at)
            VALUES (
                'categories',
                'categories',
                'v1',
                'active',
                TRUE,
                CURRENT_TIMESTAMP
            )
        ");

        $this->addSql("
            COMMENT ON TABLE {$table}
            IS 'Таблица для управления версиями и переключениями таблиц категорий'
        ");
    }

    public function down(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $table = "\"{$schemaName}\".\"catalog_table_versions\"";

        $this->addSql("
            DROP TABLE IF EXISTS {$table} CASCADE
        ");
    }
}
