<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260620214021 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Таблица categories (каталог товаров)';
    }

    public function up(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $table = "\"{$schemaName}\".\"categories\"";

        // Требуется расширение pgcrypto для gen_random_uuid()
        $this->addSql('CREATE EXTENSION IF NOT EXISTS pgcrypto');

        $this->addSql("
            CREATE TABLE {$table}
            (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY,

                uuid UUID NOT NULL,

                external_id VARCHAR(100),

                parent_external_id VARCHAR(100),

                level INTEGER NOT NULL DEFAULT 1,

                name VARCHAR(255) NOT NULL,

                slug VARCHAR(255) NOT NULL,

                is_leaf BOOLEAN NOT NULL DEFAULT FALSE,

                description TEXT,

                meta_title VARCHAR(255),

                meta_description TEXT,

                image_url VARCHAR(500),

                sort_order INTEGER NOT NULL DEFAULT 0,

                is_active BOOLEAN NOT NULL DEFAULT TRUE,

                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                CONSTRAINT categories_pkey
                    PRIMARY KEY (id),

                CONSTRAINT uq_categories_uuid
                    UNIQUE (uuid),

                CONSTRAINT uq_categories_external_id
                    UNIQUE (external_id),

                CONSTRAINT uq_categories_slug
                    UNIQUE (slug)
            )
        ");

        // Комментарии

        $this->addSql("
            COMMENT ON COLUMN {$table}.id
            IS 'Внутренний идентификатор категории'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.uuid
            IS 'Публичный UUID категории'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.external_id
            IS 'Идентификатор категории во внешней системе или CSV'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.parent_external_id
            IS 'Идентификатор родительской категории во внешней системе или CSV'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.level
            IS 'Уровень вложенности'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.name
            IS 'Название категории'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.slug
            IS 'Уникальный URL slug категории, сформированный из названия и внешнего ID'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.is_leaf
            IS 'Признак конечной категории, содержащей товары'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.description
            IS 'Описание категории'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.meta_title
            IS 'SEO title'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.meta_description
            IS 'SEO description'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.image_url
            IS 'URL изображения категории'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.sort_order
            IS 'Порядок сортировки'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.is_active
            IS 'Признак активности категории'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.created_at
            IS 'Дата создания'
        ");

        $this->addSql("
            COMMENT ON COLUMN {$table}.updated_at
            IS 'Дата последнего обновления'
        ");

        // Индексы

        $this->addSql("
            CREATE INDEX idx_categories_parent_external_id
            ON {$table}(parent_external_id)
        ");

        $this->addSql("
            CREATE INDEX idx_categories_level
            ON {$table}(level)
        ");

        $this->addSql("
            CREATE INDEX idx_categories_external_id
            ON {$table}(external_id)
        ");

        $this->addSql("
            CREATE INDEX idx_categories_slug
            ON {$table}(slug)
        ");

        $this->addSql("
            CREATE INDEX idx_categories_is_leaf
            ON {$table}(is_leaf)
        ");

        $this->addSql("
            CREATE INDEX idx_categories_sort_order
            ON {$table}(sort_order)
        ");

        $this->addSql("
            CREATE INDEX idx_categories_is_active
            ON {$table}(is_active)
        ");

        $this->addSql("
            CREATE INDEX idx_categories_parent_external_active
            ON {$table}(parent_external_id, is_active)
        ");
    }

    public function down(Schema $schema): void
    {
        $schemaName = $_ENV['DB_SCHEMA'] ?? 'public';
        $table = "\"{$schemaName}\".\"categories\"";

        $this->addSql("
            DROP TABLE IF EXISTS {$table} CASCADE
        ");
    }
}
