workspace:
    resource: ../src/Controller/WorkspaceController.php
    type: attribute
health:
    resource: ../src/Controller/ApiController.php
    type: attribute
assessment:
    resource: ../src/Controller/AssessmentController.php
    type: attribute
vacancies:
    resource: ../src/Controller/VacancyController.php
    type: attribute
public_vacancies:
    resource: ../src/Controller/PublicVacancyController.php
    type: attribute

applications:
    resource: ../src/Controller/ApplicationController.php
    type: attribute
