parameters:
    db_schema: '%env(DB_SCHEMA)%'
    app.name: '%env(APP_NAME)%'
    app.version: '%env(APP_VERSION)%'
    app.timezone: '%env(APP_TIMEZONE)%'
    jwt.issuer: '%env(JWT_CATALOG_ISSUER)%'
    jwt.audience: '%env(JWT_AUDIENCE_ACCESS_TOKEN)%'
    jwt.public_key: '%env(file:JWT_PUBLIC_KEY_FILE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Application\Workspace\:
        resource: '../src/Application/Workspace/'
    App\Infrastructure\Workspace\:
        resource: '../src/Infrastructure/Workspace/'
    App\Controller\WorkspaceController: ~
    App\Controller\AssessmentController: ~
    App\Command\AssessmentWorkCommand: ~
    App\Controller\ApiController: ~
    App\EventSubscriber\ApiExceptionSubscriber: ~
    App\Infrastructure\Security\JwtAuthenticator: ~
    App\Infrastructure\Security\JwtTokenDecoder:
        arguments:
            $publicKey: '%jwt.public_key%'
            $issuer: '%jwt.issuer%'
            $audience: '%jwt.audience%'
    App\Infrastructure\DB\SchemaSqlHelper:
        arguments:
            $schema: '%db_schema%'
    App\Infrastructure\Application\ApplicationInfo:
        arguments:
            $name: '%app.name%'
            $version: '%app.version%'
    App\Shared\Time\ClockInterface:
        alias: App\Shared\Time\SystemClock
    App\Shared\Time\SystemClock:
        arguments:
            $timezone: '%app.timezone%'
